### ISSUE TITLE
unexpected keyword argument 'locator_converter' using Appium-Python-Client 4.3.0 with BrowserStack

### ISSUE THREAD

**Issue by marcomaespolteq** [appium/python-client#1065]
## The problem

We are running a Python framework to test our app on BrowserStack. Everything went well till we updated to Appium-Python-Client 4.3.0. Now when running the BrowserStack command browserstack-sdk behave, we get the error:
HOOK-ERROR in before_scenario: TypeError: bstack1ll1lll1_opy_() got an unexpected keyword argument 'locator_converter'

Reverting back to Appium-Python-Client 4.2.1 (and therefor selenium to 4.25.0) everything started working again. Updated only selenium to 4.26.1 didn't break the test.

## Environment
- Appium version (or git revision) that exhibits the issue: 2.12.1
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium: MacOS 15.0.1 (M1 Pro)
- Node.js version (unless using Appium.app|exe): 20.17.0
- Mobile platform/version under test: Both iOS and Android
- Real device or emulator/simulator: Samsung Galaxy S22 Ultra (BrowserStack) but also iPhone 16 Pro Max (BrowserStack)
- Appium CLI or Appium.app|exe: Appium CLI

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.
https://gist.github.com/marcomaespolteq/60393e52607740e1f216419d784bacae

## Code To reproduce issue
I cloned https://github.com/browserstack/behave-appium-app-browserstack to https://github.com/marcomaespolteq/appium-python-client-issue and made the adjustments. You will need a trial of BrowserStack for this. If you clone the repo and go to the android folder, you can run browserstack-sdk behave features/first_test.feature to see it fail like described above.

**Comment by KazuCocoa** [comment]
What version of selenium dependency was referenced to?

While you set `selenium~=4.26.1` in https://github.com/marcomaespolteq/appium-python-client-issue/blob/main/requirements.txt, I guess the running env had lower than 4.26.0 since locator_converter keyword argument exist only in 4.26.0+.

Appium python client also requires 4.26.0+, thus perhaps the version itself was installed https://github.com/appium/python-client/blob/master/setup.py#L52 but the reference was not wrong


`python -m <command>` would help if the env had various version dependencies.

**Comment by KazuCocoa** [comment]
I'm not sure what `browserstack-sdk` does since they are not plain code available via pypi, but then asking their support team would be helpful rather than here.

Out CI uses `selenium = "==4.26.1"` and it passed, so probably it is argument-related thing by the SDK.
https://github.com/appium/python-client/blob/master/Pipfile
https://github.com/appium/python-client/actions/runs/11855802562/job/33040776266
