### ISSUE TITLE
[iOS] Values set using set_value method is getting cleared off when switching between pagess 

### ISSUE THREAD

**Issue by Akulavenkatesh** [appium/python-client#136]
Prerequisites: 
* Tried on iOS simulator
* Email signup form with a camera option to upload profile picture

Steps to reproduce:
1. Use any app and navigate to a page with form Eg: Email signup
2. Fill all the fields and click on the 'camera' icon
3. App navigates to a select image page to choose the picture and complete the process
4. User is automatically returned back to the Email signup form page and app waits for user to click on 'Signup' button

Expected Result:
All the filled data should be present

Actual Result:
The details filled using set_value are cleared

**Comment by Akulavenkatesh** [comment]
Found a similar issue here:
https://discuss.appium.io/t/set-value-clears-text-fields-after-setting-value/864

Also when I set_value and click next directly, the alert box says that none of the values are set. I can see the text in the fields

**Comment by Akulavenkatesh** [comment]
In the SS attached you can notice that 'Password' value is filled, but the alert box says your password should not be empty.
<img width="299" alt="issue" src="https://cloud.githubusercontent.com/assets/1756744/16390490/ab020838-3cc0-11e6-8568-78a2c25c11e3.png">

**Comment by imurchie** [comment]
The second problem is because `set_value` does not use the keyboard. It just puts the text into the element, which does not trigger any events or do any delegation. You should use `send_keys` or `keys`.

For the first problem, the server logs (as a [gist](https://gist.github.com)) might be helpful. I cannot say blindly what might be going on.

**Comment by Akulavenkatesh** [comment]
send_keys is bit slow that's why I tried using set_value. Is there any way for the values to be put on field like send_keys by using set_value? I will add the server logs to it shortly.

**Comment by Akulavenkatesh** [comment]
Server logs
https://gist.github.com/Akulavenkatesh/70babcb24184b25b69186704dfb8af7b

**Comment by imurchie** [comment]
No, there is no way. Setting the value directly is there, but there is no way to trigger the delegation.

**Comment by imurchie** [comment]
Is the filled data there if you use the app normally (i.e., manually)?

What is the effect if you use `send_keys` instead of `set_value`?

**Comment by Akulavenkatesh** [comment]
The filled data stays on screen if I enter it manually and also it stays when I use send_keys option.

What is the right places/scenarios to use set_value if there is no delegation? I thought set_value is a smart alternate to send_keys :)

**Comment by imurchie** [comment]
Unfortunately, no. `set_value` is there because some people find sending keys too slow (it is slow because it needs to make sure things go right; speeding it up exponentially increases the error rate), with the specific caveat that it does not do the normal things to your app, and does not in any way model actual user interactions.
