### ISSUE TITLE
Could not import 'webdriver' from 'appium'

### ISSUE THREAD

**Issue by EonianStar** [appium/python-client#17]
I've installed Appium Python Client from PyPi successfully and I could import appium without any error. But when I run 'from appium import webdriver', I've got the Traceback below:
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from appium import webdriver
  File "D:\Python33\lib\site-packages\appium_python_client-0.4-py3.3.egg\appium\webdriver__init__.py", line 19, in <module>
ImportError: No module named 'webdriver'
Anyone could help me on this?
Thank your very much!

**Comment by karbon62** [comment]
Hi I am receiving the same problem. Im currently using Python 2.7. I'm trying to debug the problem, honestly, Im not sure what where the folder should be placed within Python. 

This is the only reason which I could think of since its failing to register the Appium Driver each time Im running the file.

**Comment by imurchie** [comment]
Please create a new issue, with the output of your problem.

**Comment by karbon62** [comment]
Hi 

Thank you for responding - I've followed the tutorial on https://github.com/appium/python-client and it seems to have worked. 

Thanks!
