### ISSUE TITLE
Fix no appium/version.py

### ISSUE THREAD

**Issue by KazuCocoa** [appium/python-client#333]
## The problem

Maybe, missing module in the package 
Will take a look soon

## Environment
- Appium version (or git revision) that exhibits the issue:
- Last Appium version that did not exhibit the issue (if applicable):
- Desktop OS/version used to run Appium:
- Node.js version (unless using Appium.app|exe):
- Mobile platform/version under test:
- Real device or emulator/simulator:
- Appium CLI or Appium.app|exe:

## Details

If necessary, describe the problem you have been experiencing in more detail.

## Link to Appium Logs

Create a [GIST](https://gist.github.com) which is a paste of your _full_ Appium logs, and link them here.

**Comment by bowka** [comment]
I get following error of no appium/version.py. I checked that file in your repo and it has old version 0.36 can it somehow relates?
`def library_version():
        """
        Return a version of this python library
        """
        global_param = {}
        exec(
>           io.open(os.path.join(os.path.dirname('__file__'), 'appium', 'version.py'), encoding='utf-8').read(),
            global_param
        )
E       FileNotFoundError: [Errno 2] No such file or directory: 'appium/version.py'
venv/lib/python3.7/site-packages/appium/common/helper.py:46: FileNotFoundError`
this issue was definitely introduced by 0.37, I was using 0.36 and it worked well.

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/pull/332#issuecomment-462325749

**Comment by KazuCocoa** [comment]
I see...
The code does not work on the Windows file system.
https://docs.python.org/2/library/os.path.html

**Comment by KazuCocoa** [comment]
https://github.com/appium/python-client/pull/332#issuecomment-462355795
