### ISSUE TITLE
Error when I try to set location

### ISSUE THREAD

**Issue by dron4ik86** [appium/python-client#414]
## The problem
Get the error when I try to set location:
`self.driver.set_location(32.44432761840545, 34.897902299649895, None)`
`  File "/usr/local/lib/python3.7/site-packages/appium/webdriver/extensions/location.py", line 38, in set_location
    "altitude": float(altitude)
TypeError: float() argument must be a string or a number, not 'NoneType'`
Doesn't work on version 0.46 but on python-client 0.36 works fine for me.

## Environment
- Appium version (or git revision) that exhibits the issue: Appium 1.14.0
- Node.js version (unless using Appium.app|exe): v12.5.0
- Mobile platform/version under test: Android 8.1
- Real device or emulator/simulator: emulator
- Appium CLI or Appium.app|exe: CLI

**Comment by ki4070ma** [comment]
`alt` should be optional as python-client. (need fix)
If necessary, set `0` to `alt` as workaround for now.
Its error is expected on the latest version.

**Comment by KazuCocoa** [comment]
The 0.36 had `"altitude": str(altitude)`, but current one is `"altitude": float(altitude)`.
Accidentally, the previous one sent `None` to server. It worked since the `altitude` was ignored in Appium server side, in the native context.

Could you change your code as https://github.com/appium/python-client/issues/414#issuecomment-509001694 ?
Maybe, set the value as zero by default is better since it should not be optional in web context. (It is JSONWP tho. @ki4070ma )

**Comment by dron4ik86** [comment]
Thanks!
