### ISSUE TITLE
Enable device orientation change (landscape / portrait)

### ISSUE THREAD

**Issue by finspin** [appium/python-client#63]
Here is a corresponding method from java-client:

```
@Override
public void rotate(ScreenOrientation orientation) {
    execute(DriverCommand.SET_SCREEN_ORIENTATION, ImmutableMap.of(
            "orientation", orientation.value().toUpperCase()));
}
```

**Comment by ivasylchenko** [comment]
OS X 10.10.2
iPhone 6 (real device) iOS 8.2 (Safari)
appium 1.3.7
java client 2.2.0
selenium java 2.45.0

AppiumDriver.getOrientation() returns "unknown"
because Response response = execute(DriverCommand.GET_SCREEN_ORIENTATION) has "UNKNOWN" value.

Let me know if any other info needed to determine root cause of issue.

**Comment by imurchie** [comment]
Please don't add to old, closed issues.

Also, this is a server issue. See appium/appium#4725
